# Generated by Django 3.2.4 on 2021-07-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'newReg',
            },
        ),
    ]
