# Generated by Django 3.2.4 on 2021-07-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('joining_date', models.DateField(auto_now=True)),
                ('rem_leaves', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('current_project', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'addEmp',
            },
        ),
    ]
