# Generated by Django 3.2.4 on 2021-07-25 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_team_addemp_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('leaveDesc', models.TextField(max_length=300)),
                ('decision', models.CharField(default='Pending', max_length=20)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.addemp')),
            ],
            options={
                'db_table': 'leaveRequest',
            },
        ),
    ]
